# Server configuration
server:
  port: 8090

# Spring configuration
spring:
  jackson:
    serialization:
      INDENT_OUTPUT: true
  data:
    mongodb:
      uri: mongodb://springboot:springboot@192.168.2.17:3717/springboot

# JWT
jwt:
  header: Authorization
  secret: mySecret
  expiration: 604800
  tokenHead: "Bearer "
  route:
    authentication:
      path: auth
      refresh: refresh
      register: "auth/register"

# Logging configuration
logging:
  level:
    org.springframework:
      data: DEBUG
      security: DEBUG

#spring.boot.admin.url: http://localhost:8080